### ISSUE TITLE
Request: Add support for Cognito User Pools

### ISSUE THREAD

**Issue by mikedizon** [olegabu/cognito-helper#8]
Would be great to have this

https://aws.amazon.com/blogs/aws/new-user-pools-for-amazon-cognito/

**Comment by cleitonjar** [comment]
I agree.
I'm testing the cognito with user pools, this is perfect.
But authentication user inner nodejs with lambda is not working yet.
The signup, confirmationRegistration, resendConfirmationCode, changePassword e etc.
Any news in this task?

**Comment by cleitonjar** [comment]
Any news in this task?

**Comment by m-onz** [comment]
I would like cognito user pool integation too, I will submit a PR to this project if @olegabu is still maintaining it?. If this package is not being maintained I will create a separate module.

I am extremely busy atm but I will be able to submit something in a month or two... I welcome collaboration on this.

**Comment by kerenfi** [comment]
@cleitonjar can you please push your progress supporting user pools, I have some issues with the authentication

**Comment by m-onz** [comment]
I am willing to help on this... I am working in my free time (and from scratch). If there is any code to use as a starting point that would be useful if not I will create the first attempt (might take me some time - realistically in a few weeks)

**Comment by kerenfi** [comment]
I tried to add a cognito provider to current code with provider cognito-idp.eu-west-1.amazonaws.com/<pool id> so this is put in the logins map as key with the email as token  what seens to be  the wrong access token.
What I need is a basic example of login.
Can you help me with that?

**Comment by m-onz** [comment]
@kerenfi  I am really busy now but I will send some code at the end of the week. Sorry I can't help sooner. From what i've seen adding the user pool as a provider should be relatively straight foward, have you tried adding it via the AWS web interface - linking the federated identity pool with a user pool?

It should be possible to integrate with the the federated identity js library: https://www.npmjs.com/package/amazon-cognito-identity-js ... which is what I will be trying.

**Comment by jbouse** [comment]
Anyone made any progress on using the Cognito User Pools through Lambda functions? I'm looking to begin a new project and want to setup the Cognito methods through Lambda and stick it behind an API Gateway. This project seems the closest but still hadn't found anything that was updated enough to be current and using the new User Pools and all relied on developer identities.

**Comment by m-onz** [comment]
If you want to use the user pools I would just use this library:
https://www.npmjs.com/package/amazon-cognito-identity-js

I am using federated identities with cognito-helper but I had to modify it to handle custom social login providers. I ended up not using user pools because I got the functionality I needed hacking up cognito-helper. I know its possible to connect user pools to the federated identity but I have not tried that.

There is so much overlapping functionality between the older federated identity stuff and the newer user pools which makes life confusing. 

incidentally i have seen helper libraries for lambda and user pools... if you look on npm & github I think there is at least one or two.
